use DEP1_DWH
UPDATE FactBelpex
SET Belpex_RLP_MPrice =
    CASE 
	   /*WHEN DATEPART(MONTH, CAST(DateKey AS CHAR(8))) = 3 THEN XXXX   -- Maart 2024*/
       /*WHEN DATEPART(MONTH, CAST(DateKey AS CHAR(8))) = 2 THEN XXXX   -- Feb 2024*/
		WHEN DATEPART(MONTH, CAST(DateKey AS CHAR(8))) = 1 THEN 115.37  -- Jan 2025    
        WHEN DATEPART(MONTH, CAST(DateKey AS CHAR(8))) = 11 THEN 112.12 -- Nov 2024
        WHEN DATEPART(MONTH, CAST(DateKey AS CHAR(8))) = 12 THEN 108.77 -- Dec 2024
    END
WHERE Belpex_RLP_MPrice IS NULL;
